name: CI

on: push

jobs:
  lint:
    uses: jill64/reusable-workflow/.github/workflows/lint.yml@main
  check:
    uses: jill64/reusable-workflow/.github/workflows/check.yml@main
  build:
    uses: jill64/reusable-workflow/.github/workflows/build.yml@main
